{
  "public_data_at_usn": "2021-03-09T14:15:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2021-20275",
  "public_date": "2021-03-09T14:15:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-20275"
    },
    {
      "reference": "https://www.openwall.com/lists/oss-security/2021/02/28/1"
    },
    {
      "reference": "https://www.privoxy.org/gitweb/?p=privoxy.git;a=commit;h=a912ba7bc9ce5855a810d09332e9d94566ce1521"
    },
    {
      "reference": "https://ubuntu.com/security/notices/USN-4886-1"
    }
  ],
  "description": "A flaw was found in privoxy before 3.0.32. A invalid read of size two may occur in chunked_body_is_complete() leading to denial of service.",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [],
  "priority": "medium",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "privoxy",
      "release_patches": [
        {
          "release_name": "trusty",
          "status": "ignored",
          "note": "out of standard support"
        }
      ]
    }
  ],
  "upstreams": []
}
