[
  {
    "DefinitionID": "oval:org.debian:def:57119214756182467675309629700233710263",
    "Title": "CVE-2018-10879 linux",
    "Description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause a use-after-free in ext4_xattr_set_entry function and a denial of service or unspecified other impact may occur by renaming a file in a crafted ext4 filesystem image.",
    "Advisory": {
      "Severity": "",
      "Cves": [
        {
          "CveID": "CVE-2018-10879",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10879",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": {
      "MoreInfo": "",
      "Date": "1000-01-01T00:00:00Z"
    },
    "AffectedPacks": [
      {
        "Name": "linux",
        "Version": "4.17.3-1",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2018-10879",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-10879"
      }
    ]
  }
]
