[
  {
    "DefinitionID": "oval:com.ubuntu.focal:def:201612420000000",
    "Title": "CVE-2016-1242 on Ubuntu 20.04 (focal) - medium.",
    "Description": "file_open in Tryton before 3.2.17, 3.4.x before 3.4.14, 3.6.x before 3.6.12, 3.8.x before 3.8.8, and 4.x before 4.0.4 allows remote authenticated users with certain permissions to read arbitrary files via the name parameter or unspecified other vectors.",
    "Advisory": {
      "Severity": "Medium",
      "Cves": [
        {
          "CveID": "CVE-2016-1242",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1242",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [
      {
        "Name": "tryton-server",
        "Version": "4.0.4-1",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2016-1242",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1242"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-1242.html"
      },
      {
        "Source": "Bug",
        "RefID": "",
        "RefURL": "https://bugs.tryton.org/issue5808"
      }
    ]
  }
]
