[
  {
    "DefinitionID": "oval:com.ubuntu.focal:def:2019162280000000",
    "Title": "CVE-2019-16228 on Ubuntu 20.04 (focal) - medium.",
    "Description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
    "Advisory": {
      "Severity": "Medium",
      "Cves": [
        {
          "CveID": "CVE-2019-16228",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16228",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2019-16228",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16228"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "http://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-16228.html"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE"
      }
    ]
  }
]
