[
  {
    "DefinitionID": "oval:com.ubuntu.focal:def:202136200000000",
    "Title": "CVE-2021-3620 on Ubuntu 20.04 (focal) - medium.",
    "Description": "[Unknown description]",
    "Advisory": {
      "Severity": "Medium",
      "Cves": [
        {
          "CveID": "CVE-2021-3620",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3620",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [
      {
        "Name": "ansible",
        "Version": "",
        "Arch": "",
        "NotFixedYet": true,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2021-3620",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3620"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "http://people.canonical.com/~ubuntu-security/cve/2021/CVE-2021-3620.html"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://bugzilla.redhat.com/show_bug.cgi?id=1975767"
      }
    ]
  }
]
