{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2017-11368",
  "public_date": "2017-08-09T18:29:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-11368"
    },
    {
      "reference": "https://github.com/krb5/krb5/pull/678/files"
    }
  ],
  "description": "In MIT Kerberos 5 (aka krb5) 1.7 and later, an authenticated attacker can cause a KDC assertion failure by sending invalid S4U2Self or S4U2Proxy requests.",
  "ubuntu_description": "It was discovered that Kerberos incorrectly handled certain S4U2Self or S4U2Proxy requests. A remote authenticated attacker could possibly use this issue to cause a denial of service.",
  "notes": [],
  "bugs": [
    {
      "bug": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869260"
    }
  ],
  "priority": "medium",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "krb5",
      "release_patches": [
        {
          "release_name": "focal",
          "status": "not-affected",
          "note": "1.15.1-2"
        }
      ]
    }
  ],
  "upstreams": [
    {
      "package_name": "krb5",
      "upstream_links": [
        {
          "link": "https://github.com/krb5/krb5/pull/678/commits/a860385dd8fbd239fdb31b347e07f4e6b2fbdcc2"
        }
      ]
    }
  ]
}
