[
  {
    "DefinitionID": "def-main-v3.10-CVE-2020-7471",
    "Title": "CVE-2020-7471",
    "Description": "",
    "Advisory": {
      "Severity": "",
      "Cves": [
        {
          "CveID": "CVE-2020-7471",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7471",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [
      {
        "Name": "py-django",
        "Version": "1.11.28-r0",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2020-7471",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7471"
      }
    ]
  }
]
