[
  {
    "DefinitionID": "oval:com.ubuntu.bionic:def:2019160910000000",
    "Title": "CVE-2019-16091 on Ubuntu 18.04 LTS (bionic) - medium.",
    "Description": "Symonics libmysofa 0.7 has an out-of-bounds read in directblockRead in hdf/fractalhead.c.",
    "Advisory": {
      "Severity": "Medium",
      "Cves": [
        {
          "CveID": "CVE-2019-16091",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16091",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [
      {
        "Name": "libmysofa",
        "Version": "0.6~dfsg0-3+deb10u1build1",
        "Arch": "",
        "NotFixedYet": false,
        "ModularityLabel": ""
      }
    ],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2019-16091",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16091"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "http://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-16091.html"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/hoene/libmysofa/compare/f571522...e07edb3"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/hoene/libmysofa/commit/af9bbedcba2cd125fe36fa9058bd91303643472b"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/hoene/libmysofa/commit/e07edb39e9ecc796127cd748ada4a4bac88cb5d2"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://ubuntu.com/security/notices/USN-4473-1"
      },
      {
        "Source": "Bug",
        "RefID": "",
        "RefURL": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939735"
      }
    ]
  }
]
