{
  "public_data_at_usn": "2020-06-25T19:15:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2020-11538",
  "public_date": "2020-06-25T19:15:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11538"
    },
    {
      "reference": "https://github.com/python-pillow/Pillow/pull/4538"
    },
    {
      "reference": "https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html"
    },
    {
      "reference": "https://pillow.readthedocs.io/en/stable/releasenotes/index.html"
    },
    {
      "reference": "https://ubuntu.com/security/notices/USN-4430-1"
    },
    {
      "reference": "https://ubuntu.com/security/notices/USN-4430-2"
    }
  ],
  "description": "In libImaging/SgiRleDecode.c in Pillow through 7.0.0, a number of out-of-bounds reads exist in the parsing of SGI image files, a different issue than CVE-2020-5311.",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [],
  "priority": "low",
  "discovered_by": "",
  "assigned_to": "mdeslaur",
  "patches": [
    {
      "package_name": "pillow",
      "release_patches": [
        {
          "release_name": "xenial",
          "status": "not-affected",
          "note": "code not present"
        }
      ]
    },
    {
      "package_name": "pillow-python2",
      "release_patches": [
        {
          "release_name": "xenial",
          "status": "DNE",
          "note": ""
        }
      ]
    },
    {
      "package_name": "python-imaging",
      "release_patches": [
        {
          "release_name": "xenial",
          "status": "DNE",
          "note": ""
        }
      ]
    }
  ],
  "upstreams": [
    {
      "package_name": "pillow",
      "upstream_links": [
        {
          "link": "https://github.com/python-pillow/Pillow/pull/4504"
        }
      ]
    }
  ]
}
