{
  "public_data_at_usn": "0001-01-01T00:00:00Z",
  "crd": "0001-01-01T00:00:00Z",
  "candidate": "CVE-2019-16228",
  "public_date": "2019-09-11T15:15:00Z",
  "references": [
    {
      "reference": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16228"
    },
    {
      "reference": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE"
    }
  ],
  "description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
  "ubuntu_description": "",
  "notes": [],
  "bugs": [],
  "priority": "medium",
  "discovered_by": "",
  "assigned_to": "",
  "patches": [
    {
      "package_name": "py-lmdb",
      "release_patches": [
        {
          "release_name": "eoan",
          "status": "ignored",
          "note": "reached end-of-life"
        }
      ]
    }
  ],
  "upstreams": []
}
