[
  {
    "DefinitionID": "oval:com.ubuntu.xenial:def:2021326130000000",
    "Title": "CVE-2021-32613 on Ubuntu 16.04 LTS (xenial) - medium.",
    "Description": "In radare2 through 5.3.0 there is a double free vulnerability in the pyc parse via a crafted file which can lead to DoS.",
    "Advisory": {
      "Severity": "Medium",
      "Cves": [
        {
          "CveID": "CVE-2021-32613",
          "Cvss2": "",
          "Cvss3": "",
          "Cwe": "",
          "Impact": "",
          "Href": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-32613",
          "Public": ""
        }
      ],
      "Bugzillas": [],
      "AffectedCPEList": [],
      "Issued": "1000-01-01T00:00:00Z",
      "Updated": "1000-01-01T00:00:00Z"
    },
    "Debian": null,
    "AffectedPacks": [],
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2021-32613",
        "RefURL": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-32613"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "http://people.canonical.com/~ubuntu-security/cve/2021/CVE-2021-32613.html"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/radareorg/radare2/issues/18679"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://github.com/radareorg/radare2/commit/049de62730f4954ef9a642f2eeebbca30a8eccdc"
      },
      {
        "Source": "Ref",
        "RefID": "",
        "RefURL": "https://bugzilla.redhat.com/show_bug.cgi?id=1959939"
      }
    ]
  }
]
